### ISSUE TITLE
Test runs fine when run on server but when run on a remote client throws "Unhandled ImportError: No module named <module>" error

### ISSUE THREAD

**Issue by aditijha** [autotest/autotest#985] opened 2015-10-23 23:01 UTC
I have added some tests in the client/site_tests folder which refer to a python library placed in the client/shared folder. When the test is run on the server, it runs perfectly. However when I run the same test on a remote client using the following command

*server/autotest-remote -m <ip> -c client/site_tests/mytest/control*

it consistently fail with the error message

*Unhandled ImportError: No module named <module name>*

which is weird as the library package does get copied correctly in the /usr/local/autotest/shared folder on the client machine.

Am I missing something here? Isn't the shared folder right place to put common library modules referred by tests?

**Comment by lmr** [comment] 2015-10-23 23:29
Nope, wrong. `shared` doesn't get added to the python path, nor it was intended to be a common library place (if we did say that somewhere in the documentation, you must let us know). You could add the library directly to the test directory, or, if it's a shared library used by multiple test directories, put somewhere and use `sys.path.append()` shenanigans inside the control file.

**Comment by aditijha** [comment] 2015-10-26 20:19
Oh, I was going by the directory structured explained here: *http://autotest.readthedocs.org/en/latest/main/developer/DirectoryStructure.html*
 and accessing the common package as *'autotest.client.shared.mylibname'* within the test code. Thanks for clarifying.

However, even after adding *sys.path.append* statement in the control file, I am still seeing the same error message while running the tests on a client machine. Tests run fine on the server machine, but when run on a client machine using the autotest-remote command, the common library packages don't get copied to the client machine at all.

I have tried putting the library package within the home folder, site-tests folder, shared folder and client folder; changing the sys.path.append accordingly in each case, but to no avail. Please suggest the best place to put the lib package!

**Comment by lmr** [comment] 2015-10-26 21:26
Inside the test directory. Example, if your test is client/tests/sleeptest,
the libraries go inside client/tests/sleeptest.

On Mon, Oct 26, 2015 at 6:19 PM, aditijha <notifications@github.com> wrote:

> Oh, I was going by the directory structured explained here: *http://autotest.readthedocs.org/en/latest/main/developer/DirectoryStructure.html
> <http://autotest.readthedocs.org/en/latest/main/developer/DirectoryStructure.html>*
> and accessing the common package as *'autotest.client.shared.mylibname'*
> within the test code. Thanks for clarifying.
>
> However, even after adding *sys.path.append* statement in the control
> file, I am still seeing the same error message while running the tests on a
> client machine. Tests run fine on the server machine, but when run on a
> client machine using the autotest-remote command, the common library
> packages don't get copied to the client machine at all.
>
> I have tried putting the library package within the home folder,
> site-tests folder, shared folder and client folder; changing the
> sys.path.append accordingly in each case, but to no avail. Please suggest
> the best place to put the lib package!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/autotest/autotest/issues/985#issuecomment-151272736>.
>



-- 
Lucas

**Comment by aditijha** [comment] 2015-10-26 21:33
Thanks @lmr .
Apologies for not being clearer while asking the question! I have a common library package that is used by multiple tests. I created the package hierarchy as follows:

*client/site_tests/
- <common pkg>
- test1/test1.py (imports common pkg)
- test2/test2.py (imports common pkg)
...
- controlfiles/
     - control file 1 (sys.path.append('/usr/local/autotest/client/site_tests/common_pkg'))
     - control file 2 (sys.path.append('/usr/local/autotest/client/site_tests/common_pkg'))
     ...*

However this doesn't work. And I just can't get rid of common package altogether as it will result in tremendous code duplication in our tests.

**Comment by lmr** [comment] 2015-10-26 22:16
One possible solution is to package the common library as RPM/DEB/whatever
package format the distro being tested uses, and install that as part of
setup, or in the install files (kickstart, preseed or others).

On Mon, Oct 26, 2015 at 7:33 PM, aditijha <notifications@github.com> wrote:

> Thanks @lmr <https://github.com/lmr> .
> Apologies for not being clearer while asking the question! I have a common
> library package that is used by multiple tests. I created the package
> hierarchy as follows:
>
> *client/site_tests/
>
>    -
>    - test1/test1.py (imports common pkg)
>    - test2/test2.py (imports common pkg) ...
>    - controlfiles/
>       - control file 1
>       (sys.path.append('/usr/local/autotest/client/site_tests/common_pkg'))
>       - control file 2
>       (sys.path.append('/usr/local/autotest/client/site_tests/common_pkg')) ...*
>
> However this doesn't work. And I just can't get rid of common package
> altogether as it will result in tremendous code duplication in our tests.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/autotest/autotest/issues/985#issuecomment-151290955>.
>



-- 
Lucas

**Comment by lmr** [comment] 2015-10-26 22:23
Alternatively, one possible config change you could try is:

$ git diff
diff --git a/global_config.ini b/global_config.ini
index 7decc9b..bebe456 100644
--- a/global_config.ini
+++ b/global_config.ini
@@ -328,7 +328,7 @@ custom_max_age: 40
 minimum_free_space: 1

 # Whether to make autoserv the autotest package provider
-serve_packages_from_autoserv: True
+serve_packages_from_autoserv: False

 # Location to store packages
 upload_location:


If you do that, autoserv will change the way the autotest client inside
client machines, and that could solve the problem you are having about the
libraries not being found.

On Mon, Oct 26, 2015 at 8:16 PM, Lucas Meneghel Rodrigues <lookkas@gmail.com
> wrote:

> One possible solution is to package the common library as RPM/DEB/whatever
> package format the distro being tested uses, and install that as part of
> setup, or in the install files (kickstart, preseed or others).
>
> On Mon, Oct 26, 2015 at 7:33 PM, aditijha <notifications@github.com>
> wrote:
>
>> Thanks @lmr <https://github.com/lmr> .
>> Apologies for not being clearer while asking the question! I have a
>> common library package that is used by multiple tests. I created the
>> package hierarchy as follows:
>>
>> *client/site_tests/
>>
>>    -
>>    - test1/test1.py (imports common pkg)
>>    - test2/test2.py (imports common pkg) ...
>>    - controlfiles/
>>       - control file 1
>>       (sys.path.append('/usr/local/autotest/client/site_tests/common_pkg'))
>>       - control file 2
>>       (sys.path.append('/usr/local/autotest/client/site_tests/common_pkg')) ...*
>>
>> However this doesn't work. And I just can't get rid of common package
>> altogether as it will result in tremendous code duplication in our tests.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/autotest/autotest/issues/985#issuecomment-151290955>.
>>
>
>
>
> --
> Lucas
>



-- 
Lucas

**Comment by aditijha** [comment] 2015-10-26 23:13
Thanks @lmr I am trying out the second approach you suggested. 
If that doesn't work, I'll go ahead with the former approach and mount the library package on the client before running the tests.

Meanwhile, I came across this:
http://autotest.readthedocs.org/en/latest/main/developer/SiteExtensions.html
This seems to be exactly what I am looking for, however adding the name of library package in the client/common_lib/site_libraries.py still doesn't help with the package import error.

Can you please explain if this, with further exploration, can solve my problem; or is it something else entirely?

**Comment by lmr** [comment] 2015-10-26 23:23
>
>
> Meanwhile, I came across this:
>
> http://autotest.readthedocs.org/en/latest/main/developer/SiteExtensions.html
> This seems to be exactly what I am looking for, however adding the name of
> library package in the client/common_lib/site_libraries.py still doesn't
> help with the package import error.
>
> Can you please explain if this, with further exploration, can solve my
> problem; or is it something else entirely?
>
That is a poor man's plugin system. It's not what you want.

-- 
Lucas

**Comment by aditijha** [comment] 2015-10-28 16:35
Setting *'serve_packages_from_autoserv: False'* in global_config.ini didn't work for me. The modules still remain undiscoverable.
For now I am mounting the common lib package on the client machine before autotest tests are run.

**Comment by lmr** [comment] 2015-10-28 17:35
OK, glad you found a workaround. I'm closing this issue.

**Closed by lmr** 2015-10-28 17:35 UTC
